import { useState, useCallback } from 'react'
import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  ImageRun,
  AlignmentType,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
  ShadingType,
} from 'docx'
import { saveAs } from 'file-saver'

const T = {
  ko: {
    title: '보고서 내보내기',
    descLabel: '보고서 설명 (선택)',
    descPlaceholder: '예) 2025년 상반기 매출 분석 — 작성자: 홍길동',
    chartTitleLabel: '차트 제목',
    chartTitlePh: '예) 지역별 월간 매출 현황',
    authorLabel: '작성자',
    authorPh: '예) 찌에우 티 홍 응옥',
    dateLabel: '날짜',
    formatLabel: '내보내기 형식',
    exportPng: 'PNG 이미지로 저장',
    exportPdf: 'PDF 보고서로 저장',
    exportDocx: 'DOCX 보고서로 저장 (편집 가능)',
    exporting: '생성 중...',
    noChart: '먼저 차트를 생성해주세요',
    successPng: 'PNG 저장 완료!',
    successPdf: 'PDF 저장 완료!',
    successDocx: 'DOCX 저장 완료! MS Word에서 편집 가능합니다.',
    aiStory: 'AI 분석 결과',
    reportTitle: '데이터 분석 보고서',
    generatedBy: '생성: 스마트 차트 빌더',
    insightsTitle: '핵심 인사이트',
    storyTitle: '데이터 스토리',
    recommendTitle: '권고사항',
    roadmapTitle: '전략 로드맵',
    comprehensiveReport: '종합 보고서',
  },
  vi: {
    title: 'Xuất báo cáo',
    descLabel: 'Mô tả báo cáo (tuỳ chọn)',
    descPlaceholder: 'Ví dụ: Báo cáo doanh thu Q1 2025 — Tác giả: Nguyễn Văn A',
    chartTitleLabel: 'Tiêu đề biểu đồ',
    chartTitlePh: 'Ví dụ: Doanh thu theo khu vực',
    authorLabel: 'Tác giả',
    authorPh: 'Ví dụ: Triệu Thị Hồng Ngọc',
    dateLabel: 'Ngày',
    formatLabel: 'Định dạng xuất',
    exportPng: 'Lưu ảnh PNG',
    exportPdf: 'Lưu báo cáo PDF',
    exportDocx: 'Lưu báo cáo DOCX (chỉnh sửa được)',
    exporting: 'Đang tạo...',
    noChart: 'Vui lòng tạo biểu đồ trước',
    successPng: 'Đã lưu PNG!',
    successPdf: 'Đã lưu PDF!',
    successDocx: 'Đã lưu DOCX! Có thể chỉnh sửa trong MS Word.',
    aiStory: 'Phân tích AI',
    reportTitle: 'Báo cáo Phân tích Dữ liệu',
    generatedBy: 'Tạo bởi: Smart Chart Builder',
    insightsTitle: 'Thông tin chính',
    storyTitle: 'Câu chuyện dữ liệu',
    recommendTitle: 'Đề xuất',
    roadmapTitle: 'Lộ trình chiến lược',
    comprehensiveReport: 'Báo cáo tổng hợp',
  },
  en: {
    title: 'Export Report',
    descLabel: 'Report Description (optional)',
    descPlaceholder: 'e.g. H1 2025 Sales Report — Author: Jane Doe',
    chartTitleLabel: 'Chart Title',
    chartTitlePh: 'e.g. Monthly Revenue by Region',
    authorLabel: 'Author',
    authorPh: 'e.g. Trieu Thi Hong Ngoc',
    dateLabel: 'Date',
    formatLabel: 'Export Format',
    exportPng: 'Save as PNG',
    exportPdf: 'Save as PDF Report',
    exportDocx: 'Save as DOCX Report (Editable)',
    exporting: 'Generating...',
    noChart: 'Please create a chart first',
    successPng: 'PNG saved!',
    successPdf: 'PDF saved!',
    successDocx: 'DOCX saved! You can edit it in MS Word.',
    aiStory: 'AI Analysis',
    reportTitle: 'Data Analysis Report',
    generatedBy: 'Generated by: Smart Chart Builder',
    insightsTitle: 'Key Insights',
    storyTitle: 'Data Story',
    recommendTitle: 'Recommendation',
    roadmapTitle: 'Strategic Roadmap',
    comprehensiveReport: 'Comprehensive Report',
  },
}

function base64ToUint8Array(base64) {
  const binaryString = atob(base64)
  const bytes = new Uint8Array(binaryString.length)
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i)
  }
  return bytes
}

export default function ExportPanel({ lang = 'ko', chartContainerId = 'chart-container', aiStory, chartConfig }) {
  const t = T[lang] || T.ko
  const today = new Date().toLocaleDateString(
    lang === 'ko' ? 'ko-KR' : lang === 'vi' ? 'vi-VN' : 'en-US'
  )

  const [description, setDescription] = useState('')
  const [customTitle, setCustomTitle] = useState('')
  const [author, setAuthor] = useState('')
  const [date, setDate] = useState(today)
  const [exporting, setExporting] = useState(false)
  const [toast, setToast] = useState(null)

  const showToast = (msg, ok = true) => {
    setToast({ msg, ok })
    setTimeout(() => setToast(null), 4000)
  }

  const getChartEl = () => {
    const el = document.getElementById(chartContainerId)
    if (!el) { alert(t.noChart); return null }
    return el
  }

  const getChartBase64 = () => {
    const container = document.getElementById(chartContainerId)
    if (!container) return null
    const canvas = container.querySelector('canvas')
    if (!canvas) return null
    return canvas.toDataURL('image/png').replace(/^data:image\/png;base64,/, '')
  }

  const exportPNG = async () => {
    const el = getChartEl()
    if (!el) return
    setExporting(true)
    try {
      const canvas = await html2canvas(el, {
        scale: 2,
        useCORS: true,
        windowWidth: 800,
        onclone: (doc) => {
          const clonedEl = doc.getElementById(chartContainerId)
          if (clonedEl) clonedEl.style.width = '800px'
        }
      })
      const link = document.createElement('a')
      const fileName = (customTitle || 'chart').replace(/\s+/g, '_')
      link.download = `${fileName}_${date.replace(/\//g, '-')}.png`
      link.href = canvas.toDataURL('image/png')
      link.click()
      showToast(t.successPng)
    } catch (e) {
      showToast('오류: ' + e.message, false)
    } finally {
      setExporting(false)
    }
  }

  const exportPDF = async () => {
    const el = getChartEl()
    if (!el) return
    setExporting(true)
    try {
      const canvas = await html2canvas(el, {
        scale: 2,
        useCORS: true,
        windowWidth: 800,
        onclone: (doc) => {
          const clonedEl = doc.getElementById(chartContainerId)
          if (clonedEl) clonedEl.style.width = '800px'
        }
      })
      const pdf = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' })
      let y = 15

      // Header
      pdf.setFillColor(83, 74, 183)
      pdf.rect(0, 0, 210, 28, 'F')
      pdf.setTextColor(255, 255, 255)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text(customTitle || t.reportTitle, 14, 12)
      pdf.setFontSize(9)
      pdf.setFont('helvetica', 'normal')
      pdf.text(t.generatedBy, 14, 21)
      pdf.setTextColor(0, 0, 0)
      y = 35

      // Meta
      pdf.setFontSize(9)
      pdf.setTextColor(100, 100, 100)
      if (author) { pdf.text(`${t.authorLabel}: ${author}`, 14, y); y += 6 }
      pdf.text(`${t.dateLabel}: ${date}`, 14, y); y += 6
      if (description) {
        pdf.setTextColor(50, 50, 50)
        pdf.setFontSize(10)
        const lines = pdf.splitTextToSize(description, 182)
        pdf.text(lines, 14, y)
        y += lines.length * 5 + 4
      }

      // Divider
      pdf.setDrawColor(200, 200, 200)
      pdf.line(14, y, 196, y); y += 6

      // Chart image
      const imgW = 182
      const imgH = Math.min((canvas.height / canvas.width) * imgW, 110)
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 14, y, imgW, imgH)
      y += imgH + 8

      // AI Story
      if (aiStory?.story) {
        pdf.setFillColor(225, 245, 238)
        pdf.roundedRect(14, y, 182, 8, 2, 2, 'F')
        pdf.setTextColor(8, 80, 65)
        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'bold')
        pdf.text(t.aiStory, 18, y + 5.5)
        y += 12
        pdf.setFont('helvetica', 'normal')
        pdf.setFontSize(9)
        pdf.setTextColor(50, 50, 50)
        const storyLines = pdf.splitTextToSize(aiStory.story, 178)
        pdf.text(storyLines, 16, y)
        y += storyLines.length * 4.5 + 6
      }

      // AI Insights cards
      if (aiStory?.insights?.length) {
        const colorMap = {
          positive: [225, 245, 238],
          negative: [252, 235, 235],
          neutral: [238, 237, 254],
        }
        aiStory.insights.forEach((ins, i) => {
          const c = colorMap[ins.type] || colorMap.neutral
          const x = 14 + i * 62
          pdf.setFillColor(...c)
          pdf.roundedRect(x, y, 58, 16, 2, 2, 'F')
          pdf.setFontSize(11)
          pdf.setFont('helvetica', 'bold')
          pdf.setTextColor(50, 50, 50)
          pdf.text(String(ins.value), x + 29, y + 7, { align: 'center' })
          pdf.setFontSize(8)
          pdf.setFont('helvetica', 'normal')
          pdf.text(String(ins.label), x + 29, y + 13, { align: 'center' })
        })
        y += 22
      }

      // Footer
      pdf.setFontSize(8)
      pdf.setTextColor(160, 160, 160)
      pdf.text(`Smart Chart Builder  |  ${date}`, 105, 287, { align: 'center' })

      const fileName = (customTitle || 'report').replace(/\s+/g, '_')
      pdf.save(`${fileName}_${date.replace(/\//g, '-')}.pdf`)
      showToast(t.successPdf)
    } catch (e) {
      showToast('PDF 오류: ' + e.message, false)
    } finally {
      setExporting(false)
    }
  }

  const exportDOCX = useCallback(async () => {
    setExporting(true)
    try {
      const chartBase64 = getChartBase64()
      const children = []
      const title = customTitle || chartConfig?.title || t.reportTitle

      // ── Title ──
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: title,
              bold: true,
              size: 48,
              color: '534AB7',
              font: 'Calibri',
            }),
          ],
          spacing: { after: 100 },
          alignment: AlignmentType.CENTER,
        })
      )

      // ── Meta info ──
      const metaParts = []
      if (author) metaParts.push(`${t.authorLabel}: ${author}`)
      metaParts.push(`${t.dateLabel}: ${date}`)
      metaParts.push(t.generatedBy)

      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: metaParts.join('  |  '),
              size: 20,
              color: '888888',
              font: 'Calibri',
            }),
          ],
          spacing: { after: 200 },
          alignment: AlignmentType.CENTER,
        })
      )

      // ── Description ──
      if (description) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: description,
                size: 22,
                color: '555555',
                font: 'Calibri',
                italics: true,
              }),
            ],
            spacing: { after: 200 },
            alignment: AlignmentType.CENTER,
          })
        )
      }

      // ── Divider ──
      children.push(
        new Paragraph({
          border: {
            bottom: { color: 'CCCCCC', space: 1, style: BorderStyle.SINGLE, size: 6 },
          },
          spacing: { after: 300 },
        })
      )

      // ── Chart Image ──
      if (chartBase64) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: '📊 Chart',
                bold: true,
                size: 28,
                color: '0F6E56',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 200 },
          })
        )

        const imgBytes = base64ToUint8Array(chartBase64)
        children.push(
          new Paragraph({
            children: [
              new ImageRun({
                data: imgBytes,
                transformation: { width: 580, height: 350 },
                type: 'png',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 300 },
          })
        )
      }

      // ── Insights Table ──
      if (aiStory?.insights?.length) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `💡 ${t.insightsTitle}`,
                bold: true,
                size: 28,
                color: '534AB7',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 200 },
          })
        )

        const insightRows = aiStory.insights.map((ins) => {
          const colorMap = { positive: 'E1F5EE', negative: 'FCEBEB', neutral: 'EEEDFE' }
          const textColorMap = { positive: '085041', negative: 'A32D2D', neutral: '3C3489' }
          const iconMap = { positive: '✅', negative: '⚠️', neutral: 'ℹ️' }

          return new TableRow({
            children: [
              new TableCell({
                children: [
                  new Paragraph({
                    children: [new TextRun({ text: iconMap[ins.type] || 'ℹ️', size: 24 })],
                    alignment: AlignmentType.CENTER,
                  }),
                ],
                width: { size: 800, type: WidthType.DXA },
                shading: { type: ShadingType.SOLID, color: colorMap[ins.type] || 'EEEDFE' },
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: ins.label,
                        bold: true,
                        size: 22,
                        color: textColorMap[ins.type] || '333333',
                        font: 'Calibri',
                      }),
                    ],
                  }),
                ],
                width: { size: 3600, type: WidthType.DXA },
                shading: { type: ShadingType.SOLID, color: colorMap[ins.type] || 'EEEDFE' },
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: String(ins.value),
                        bold: true,
                        size: 24,
                        color: textColorMap[ins.type] || '333333',
                        font: 'Calibri',
                      }),
                    ],
                    alignment: AlignmentType.RIGHT,
                  }),
                ],
                width: { size: 4600, type: WidthType.DXA },
                shading: { type: ShadingType.SOLID, color: colorMap[ins.type] || 'EEEDFE' },
              }),
            ],
          })
        })

        children.push(
          new Table({
            rows: insightRows,
            width: { size: 100, type: WidthType.PERCENTAGE },
          })
        )
        children.push(new Paragraph({ spacing: { after: 300 } }))
      }

      // ── Data Story ──
      if (aiStory?.story) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `📖 ${t.storyTitle}`,
                bold: true,
                size: 28,
                color: '085041',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 100 },
          })
        )
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: aiStory.story,
                size: 22,
                color: '333333',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 300 },
            border: {
              left: { color: '9FE1CB', space: 5, style: BorderStyle.SINGLE, size: 12 },
            },
            indent: { left: 300 },
          })
        )
      }

      // ── Recommendation ──
      if (aiStory?.recommendation) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `🎯 ${t.recommendTitle}`,
                bold: true,
                size: 28,
                color: '534AB7',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 100 },
          })
        )
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: aiStory.recommendation,
                size: 22,
                color: '333333',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 300 },
            border: {
              left: { color: 'AFA9EC', space: 5, style: BorderStyle.SINGLE, size: 12 },
            },
            indent: { left: 300 },
          })
        )
      }

      // ── Roadmap ──
      if (aiStory?.roadmap) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `🗺️ ${t.roadmapTitle}`,
                bold: true,
                size: 28,
                color: '856404',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 100 },
          })
        )
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: aiStory.roadmap,
                size: 22,
                color: '333333',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 300 },
            border: {
              left: { color: 'FFEAA7', space: 5, style: BorderStyle.SINGLE, size: 12 },
            },
            indent: { left: 300 },
          })
        )
      }

      // ── Comprehensive Report ──
      if (aiStory?.report) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `📑 ${t.comprehensiveReport}`,
                bold: true,
                size: 28,
                color: '0C5460',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 100 },
          })
        )
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: aiStory.report,
                size: 22,
                color: '333333',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 300 },
            border: {
              left: { color: 'BEE5EB', space: 5, style: BorderStyle.SINGLE, size: 12 },
            },
            indent: { left: 300 },
          })
        )
      }

      // ── Footer ──
      children.push(
        new Paragraph({
          border: {
            top: { color: 'CCCCCC', space: 1, style: BorderStyle.SINGLE, size: 6 },
          },
          spacing: { before: 400, after: 100 },
        })
      )
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `Smart Chart Builder  |  ${date}`,
              size: 16,
              color: 'AAAAAA',
              font: 'Calibri',
            }),
          ],
          alignment: AlignmentType.CENTER,
        })
      )

      const doc = new Document({
        sections: [{
          properties: {
            page: { margin: { top: 720, bottom: 720, left: 720, right: 720 } },
          },
          children,
        }],
      })

      const blob = await Packer.toBlob(doc)
      const fileName = (title).replace(/\s+/g, '_')
      saveAs(blob, `${fileName}_${date.replace(/\//g, '-')}.docx`)
      showToast(t.successDocx)
    } catch (e) {
      console.error('DOCX error:', e)
      showToast('DOCX Error: ' + e.message, false)
    } finally {
      setExporting(false)
    }
  }, [customTitle, author, date, description, aiStory, chartConfig, chartContainerId, lang, t])

  const inputStyle = {
    width: '100%', padding: '7px 10px', fontSize: 12,
    border: '1px solid #ddd', borderRadius: 7,
    outline: 'none', background: '#fafafa', fontFamily: 'inherit',
    marginTop: 3,
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
        <span style={{ fontSize: 14 }}>📥</span>
        <span style={{ fontSize: 12, fontWeight: 500 }}>{t.title}</span>
      </div>

      <div>
        <label style={{ fontSize: 11, fontWeight: 500, color: '#555' }}>{t.chartTitleLabel}</label>
        <input style={inputStyle} placeholder={t.chartTitlePh} value={customTitle} onChange={e => setCustomTitle(e.target.value)} />
      </div>

      <div>
        <label style={{ fontSize: 11, fontWeight: 500, color: '#555' }}>{t.descLabel}</label>
        <textarea style={{ ...inputStyle, resize: 'vertical', minHeight: 60, lineHeight: 1.5 }} placeholder={t.descPlaceholder} value={description} onChange={e => setDescription(e.target.value)} />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
        <div>
          <label style={{ fontSize: 11, fontWeight: 500, color: '#555' }}>{t.authorLabel}</label>
          <input style={inputStyle} placeholder={t.authorPh} value={author} onChange={e => setAuthor(e.target.value)} />
        </div>
        <div>
          <label style={{ fontSize: 11, fontWeight: 500, color: '#555' }}>{t.dateLabel}</label>
          <input style={inputStyle} value={date} onChange={e => setDate(e.target.value)} />
        </div>
      </div>

      <div style={{ borderTop: '1px solid #eee', paddingTop: 8 }}>
        <div style={{ fontSize: 11, fontWeight: 500, color: '#555', marginBottom: 8 }}>{t.formatLabel}</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
          <button disabled={exporting} onClick={exportPNG}
            style={{ padding: '9px', border: 'none', borderRadius: 8, cursor: exporting ? 'not-allowed' : 'pointer', background: exporting ? '#bbb' : '#534AB7', color: '#fff', fontSize: 12, fontWeight: 500 }}>
            {exporting ? t.exporting : `🖼️ ${t.exportPng}`}
          </button>
          <button disabled={exporting} onClick={exportPDF}
            style={{ padding: '9px', border: 'none', borderRadius: 8, cursor: exporting ? 'not-allowed' : 'pointer', background: exporting ? '#bbb' : '#0F6E56', color: '#fff', fontSize: 12, fontWeight: 500 }}>
            {exporting ? t.exporting : `📄 ${t.exportPdf}`}
          </button>
          <button disabled={exporting} onClick={exportDOCX}
            style={{
              padding: '9px', border: 'none', borderRadius: 8,
              cursor: exporting ? 'not-allowed' : 'pointer',
              background: exporting ? '#bbb' : 'linear-gradient(135deg, #2B5797, #4A90D9)',
              color: '#fff', fontSize: 12, fontWeight: 500,
              boxShadow: exporting ? 'none' : '0 2px 6px rgba(43,87,151,0.3)',
              transition: 'all 0.2s ease',
            }}>
            {exporting ? t.exporting : `📝 ${t.exportDocx}`}
          </button>
        </div>

        {/* DOCX info note */}
        <div style={{
          marginTop: 8, fontSize: 10, color: '#666',
          background: '#f0f4ff', border: '1px solid #d0d8f0',
          borderRadius: 6, padding: '6px 8px', lineHeight: 1.5,
        }}>
          💡 {lang === 'ko' ? 'DOCX: 차트 + AI분석 포함, MS Word에서 바로 편집 가능'
              : lang === 'vi' ? 'DOCX: Bao gồm biểu đồ + AI, chỉnh sửa được trong MS Word'
              : 'DOCX: Includes chart + AI analysis, editable in MS Word'}
        </div>
      </div>

      {toast && (
        <div style={{ padding: '8px 12px', borderRadius: 7, fontSize: 12, textAlign: 'center', background: toast.ok ? '#E1F5EE' : '#FCEBEB', color: toast.ok ? '#085041' : '#A32D2D', border: `1px solid ${toast.ok ? '#9FE1CB' : '#F7C1C1'}` }}>
          {toast.msg}
        </div>
      )}
    </div>
  )
}