import { useState } from 'react'
import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'

const T = {
  ko: {
    title: '보고서 내보내기',
    descLabel: '보고서 설명 (선택)',
    descPlaceholder: '예) 2025년 상반기 매출 분석 — 작성자: 홍길동',
    chartTitleLabel: '차트 제목',
    chartTitlePh: '예) 지역별 월간 매출 현황',
    authorLabel: '작성자',
    authorPh: '예) 찌에우 티 홍 응옥',
    dateLabel: '날짜',
    formatLabel: '내보내기 형식',
    exportPng: 'PNG 이미지로 저장',
    exportPdf: 'PDF 보고서로 저장',
    exporting: '생성 중...',
    noChart: '먼저 차트를 생성해주세요',
    successPng: 'PNG 저장 완료!',
    successPdf: 'PDF 저장 완료!',
    aiStory: 'AI 분석 결과',
    reportTitle: '데이터 분석 보고서',
    generatedBy: '생성: 스마트 차트 빌더',
  },
  vi: {
    title: 'Xuất báo cáo',
    descLabel: 'Mô tả báo cáo (tuỳ chọn)',
    descPlaceholder: 'Ví dụ: Báo cáo doanh thu Q1 2025 — Tác giả: Nguyễn Văn A',
    chartTitleLabel: 'Tiêu đề biểu đồ',
    chartTitlePh: 'Ví dụ: Doanh thu theo khu vực',
    authorLabel: 'Tác giả',
    authorPh: 'Ví dụ: Triệu Thị Hồng Ngọc',
    dateLabel: 'Ngày',
    formatLabel: 'Định dạng xuất',
    exportPng: 'Lưu ảnh PNG',
    exportPdf: 'Lưu báo cáo PDF',
    exporting: 'Đang tạo...',
    noChart: 'Vui lòng tạo biểu đồ trước',
    successPng: 'Đã lưu PNG!',
    successPdf: 'Đã lưu PDF!',
    aiStory: 'Phân tích AI',
    reportTitle: 'Báo cáo Phân tích Dữ liệu',
    generatedBy: 'Tạo bởi: Smart Chart Builder',
  },
  en: {
    title: 'Export Report',
    descLabel: 'Report Description (optional)',
    descPlaceholder: 'e.g. H1 2025 Sales Report — Author: Jane Doe',
    chartTitleLabel: 'Chart Title',
    chartTitlePh: 'e.g. Monthly Revenue by Region',
    authorLabel: 'Author',
    authorPh: 'e.g. Trieu Thi Hong Ngoc',
    dateLabel: 'Date',
    formatLabel: 'Export Format',
    exportPng: 'Save as PNG',
    exportPdf: 'Save as PDF Report',
    exporting: 'Generating...',
    noChart: 'Please create a chart first',
    successPng: 'PNG saved!',
    successPdf: 'PDF saved!',
    aiStory: 'AI Analysis',
    reportTitle: 'Data Analysis Report',
    generatedBy: 'Generated by: Smart Chart Builder',
  },
}

export default function ExportPanel({ lang = 'ko', chartContainerId = 'chart-container', aiStory, chartConfig }) {
  const t = T[lang] || T.ko
  const today = new Date().toLocaleDateString(
    lang === 'ko' ? 'ko-KR' : lang === 'vi' ? 'vi-VN' : 'en-US'
  )

  const [description, setDescription] = useState('')
  const [customTitle, setCustomTitle] = useState('')
  const [author, setAuthor] = useState('')
  const [date, setDate] = useState(today)
  const [exporting, setExporting] = useState(false)
  const [toast, setToast] = useState(null)

  const showToast = (msg, ok = true) => {
    setToast({ msg, ok })
    setTimeout(() => setToast(null), 3000)
  }

  const getChartEl = () => {
    const el = document.getElementById(chartContainerId)
    if (!el) { alert(t.noChart); return null }
    return el
  }

  const exportPNG = async () => {
    const el = getChartEl()
    if (!el) return
    setExporting(true)
    try {
      const canvas = await html2canvas(el, { scale: 2, useCORS: true })
      const link = document.createElement('a')
      const fileName = (customTitle || 'chart').replace(/\s+/g, '_')
      link.download = `${fileName}_${date.replace(/\//g, '-')}.png`
      link.href = canvas.toDataURL('image/png')
      link.click()
      showToast(t.successPng)
    } catch (e) {
      showToast('오류: ' + e.message, false)
    } finally {
      setExporting(false)
    }
  }

  const exportPDF = async () => {
    const el = getChartEl()
    if (!el) return
    setExporting(true)
    try {
      const canvas = await html2canvas(el, { scale: 2, useCORS: true })
      const pdf = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' })
      let y = 15

      // Header
      pdf.setFillColor(83, 74, 183)
      pdf.rect(0, 0, 210, 28, 'F')
      pdf.setTextColor(255, 255, 255)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text(customTitle || t.reportTitle, 14, 12)
      pdf.setFontSize(9)
      pdf.setFont('helvetica', 'normal')
      pdf.text(t.generatedBy, 14, 21)
      pdf.setTextColor(0, 0, 0)
      y = 35

      // Meta
      pdf.setFontSize(9)
      pdf.setTextColor(100, 100, 100)
      if (author) { pdf.text(`${t.authorLabel}: ${author}`, 14, y); y += 6 }
      pdf.text(`${t.dateLabel}: ${date}`, 14, y); y += 6
      if (description) {
        pdf.setTextColor(50, 50, 50)
        pdf.setFontSize(10)
        const lines = pdf.splitTextToSize(description, 182)
        pdf.text(lines, 14, y)
        y += lines.length * 5 + 4
      }

      // Divider
      pdf.setDrawColor(200, 200, 200)
      pdf.line(14, y, 196, y); y += 6

      // Chart image
      const imgW = 182
      const imgH = Math.min((canvas.height / canvas.width) * imgW, 110)
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 14, y, imgW, imgH)
      y += imgH + 8

      // AI Story
      if (aiStory?.story) {
        pdf.setFillColor(225, 245, 238)
        pdf.roundedRect(14, y, 182, 8, 2, 2, 'F')
        pdf.setTextColor(8, 80, 65)
        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'bold')
        pdf.text(t.aiStory, 18, y + 5.5)
        y += 12
        pdf.setFont('helvetica', 'normal')
        pdf.setFontSize(9)
        pdf.setTextColor(50, 50, 50)
        const storyLines = pdf.splitTextToSize(aiStory.story, 178)
        pdf.text(storyLines, 16, y)
        y += storyLines.length * 4.5 + 6
      }

      // AI Insights cards
      if (aiStory?.insights?.length) {
        const colorMap = {
          positive: [225, 245, 238],
          negative: [252, 235, 235],
          neutral: [238, 237, 254],
        }
        aiStory.insights.forEach((ins, i) => {
          const c = colorMap[ins.type] || colorMap.neutral
          const x = 14 + i * 62
          pdf.setFillColor(...c)
          pdf.roundedRect(x, y, 58, 16, 2, 2, 'F')
          pdf.setFontSize(11)
          pdf.setFont('helvetica', 'bold')
          pdf.setTextColor(50, 50, 50)
          pdf.text(String(ins.value), x + 29, y + 7, { align: 'center' })
          pdf.setFontSize(8)
          pdf.setFont('helvetica', 'normal')
          pdf.text(String(ins.label), x + 29, y + 13, { align: 'center' })
        })
        y += 22
      }

      // Footer
      pdf.setFontSize(8)
      pdf.setTextColor(160, 160, 160)
      pdf.text(`Smart Chart Builder  |  ${date}`, 105, 287, { align: 'center' })

      const fileName = (customTitle || 'report').replace(/\s+/g, '_')
      pdf.save(`${fileName}_${date.replace(/\//g, '-')}.pdf`)
      showToast(t.successPdf)
    } catch (e) {
      showToast('PDF 오류: ' + e.message, false)
    } finally {
      setExporting(false)
    }
  }

  const inputStyle = {
    width: '100%', padding: '7px 10px', fontSize: 12,
    border: '1px solid #ddd', borderRadius: 7,
    outline: 'none', background: '#fafafa', fontFamily: 'inherit',
    marginTop: 3,
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
        <span style={{ fontSize: 14 }}>📥</span>
        <span style={{ fontSize: 12, fontWeight: 500 }}>{t.title}</span>
      </div>

      <div>
        <label style={{ fontSize: 11, fontWeight: 500, color: '#555' }}>{t.chartTitleLabel}</label>
        <input style={inputStyle} placeholder={t.chartTitlePh} value={customTitle} onChange={e => setCustomTitle(e.target.value)} />
      </div>

      <div>
        <label style={{ fontSize: 11, fontWeight: 500, color: '#555' }}>{t.descLabel}</label>
        <textarea style={{ ...inputStyle, resize: 'vertical', minHeight: 60, lineHeight: 1.5 }} placeholder={t.descPlaceholder} value={description} onChange={e => setDescription(e.target.value)} />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
        <div>
          <label style={{ fontSize: 11, fontWeight: 500, color: '#555' }}>{t.authorLabel}</label>
          <input style={inputStyle} placeholder={t.authorPh} value={author} onChange={e => setAuthor(e.target.value)} />
        </div>
        <div>
          <label style={{ fontSize: 11, fontWeight: 500, color: '#555' }}>{t.dateLabel}</label>
          <input style={inputStyle} value={date} onChange={e => setDate(e.target.value)} />
        </div>
      </div>

      <div style={{ borderTop: '1px solid #eee', paddingTop: 8 }}>
        <div style={{ fontSize: 11, fontWeight: 500, color: '#555', marginBottom: 8 }}>{t.formatLabel}</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
          <button disabled={exporting} onClick={exportPNG}
            style={{ padding: '9px', border: 'none', borderRadius: 8, cursor: exporting ? 'not-allowed' : 'pointer', background: exporting ? '#bbb' : '#534AB7', color: '#fff', fontSize: 12, fontWeight: 500 }}>
            {exporting ? t.exporting : `🖼️ ${t.exportPng}`}
          </button>
          <button disabled={exporting} onClick={exportPDF}
            style={{ padding: '9px', border: 'none', borderRadius: 8, cursor: exporting ? 'not-allowed' : 'pointer', background: exporting ? '#bbb' : '#0F6E56', color: '#fff', fontSize: 12, fontWeight: 500 }}>
            {exporting ? t.exporting : `📄 ${t.exportPdf}`}
          </button>
        </div>
      </div>

      {toast && (
        <div style={{ padding: '8px 12px', borderRadius: 7, fontSize: 12, textAlign: 'center', background: toast.ok ? '#E1F5EE' : '#FCEBEB', color: toast.ok ? '#085041' : '#A32D2D', border: `1px solid ${toast.ok ? '#9FE1CB' : '#F7C1C1'}` }}>
          {toast.msg}
        </div>
      )}
    </div>
  )
}