import { useState, useRef, useCallback } from 'react'
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  ImageRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
  ShadingType,
  TabStopPosition,
  TabStopType,
  PageBreak,
} from 'docx'
import { saveAs } from 'file-saver'

const T = {
  ko: {
    title: '📋 보고서 미리보기',
    download: '📥 DOCX 다운로드',
    downloading: '생성 중...',
    noData: '차트와 AI 스토리를 먼저 생성해주세요',
    chartTitle: '데이터 시각화',
    storyTitle: '데이터 스토리',
    insightsTitle: '핵심 인사이트',
    recommendTitle: '권고사항',
    roadmapTitle: '전략 로드맵',
    reportTitle: '종합 보고서',
    generatedBy: '생성: Smart Chart Builder',
    editNote: '※ 다운로드한 DOCX 파일은 MS Word에서 바로 편집 가능합니다',
  },
  vi: {
    title: '📋 Xem trước báo cáo',
    download: '📥 Tải DOCX',
    downloading: 'Đang tạo...',
    noData: 'Vui lòng tạo biểu đồ và AI Story trước',
    chartTitle: 'Trực quan hóa dữ liệu',
    storyTitle: 'Câu chuyện dữ liệu',
    insightsTitle: 'Thông tin chính',
    recommendTitle: 'Đề xuất',
    roadmapTitle: 'Lộ trình chiến lược',
    reportTitle: 'Báo cáo tổng hợp',
    generatedBy: 'Tạo bởi: Smart Chart Builder',
    editNote: '※ File DOCX có thể chỉnh sửa ngay trong MS Word',
  },
  en: {
    title: '📋 Report Preview',
    download: '📥 Download DOCX',
    downloading: 'Generating...',
    noData: 'Please create a chart and AI Story first',
    chartTitle: 'Data Visualization',
    storyTitle: 'Data Story',
    insightsTitle: 'Key Insights',
    recommendTitle: 'Recommendation',
    roadmapTitle: 'Strategic Roadmap',
    reportTitle: 'Comprehensive Report',
    generatedBy: 'Generated by: Smart Chart Builder',
    editNote: '※ Downloaded DOCX file can be edited directly in MS Word',
  },
}

const INSIGHT_COLORS = {
  positive: { bg: '#E1F5EE', text: '#085041', border: '#9FE1CB', label: '✅' },
  negative: { bg: '#FCEBEB', text: '#A32D2D', border: '#F7C1C1', label: '⚠️' },
  neutral:  { bg: '#EEEDFE', text: '#3C3489', border: '#AFA9EC', label: 'ℹ️' },
}

/**
 * Captures the chart canvas as a base64 PNG image (without the data:image/png;base64, prefix).
 */
function getChartImageBase64(chartContainerId) {
  const container = document.getElementById(chartContainerId)
  if (!container) return null
  const canvas = container.querySelector('canvas')
  if (!canvas) return null
  const dataUrl = canvas.toDataURL('image/png')
  // strip prefix
  return dataUrl.replace(/^data:image\/png;base64,/, '')
}

/**
 * Converts base64 string to Uint8Array for docx ImageRun
 */
function base64ToUint8Array(base64) {
  const binaryString = atob(base64)
  const bytes = new Uint8Array(binaryString.length)
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i)
  }
  return bytes
}

export default function ReportBuilder({
  lang = 'ko',
  chartConfig,
  aiStory,
  chartContainerId = 'chart-container',
}) {
  const t = T[lang] || T.ko
  const [downloading, setDownloading] = useState(false)

  const canExport = chartConfig && aiStory

  const generateDocx = useCallback(async () => {
    if (!canExport) return
    setDownloading(true)

    try {
      const chartBase64 = getChartImageBase64(chartContainerId)

      const children = []

      // ── Title Page Header ──
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: chartConfig.title || t.reportTitle,
              bold: true,
              size: 48,
              color: '534AB7',
              font: 'Calibri',
            }),
          ],
          spacing: { after: 100 },
          alignment: AlignmentType.CENTER,
        })
      )

      // Subtitle / metadata
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: t.generatedBy,
              size: 20,
              color: '888888',
              font: 'Calibri',
            }),
            new TextRun({
              text: `  |  ${new Date().toLocaleDateString(
                lang === 'ko' ? 'ko-KR' : lang === 'vi' ? 'vi-VN' : 'en-US'
              )}`,
              size: 20,
              color: '888888',
              font: 'Calibri',
            }),
          ],
          spacing: { after: 300 },
          alignment: AlignmentType.CENTER,
        })
      )

      // ── Divider ──
      children.push(
        new Paragraph({
          border: {
            bottom: { color: 'CCCCCC', space: 1, style: BorderStyle.SINGLE, size: 6 },
          },
          spacing: { after: 300 },
        })
      )

      // ── Chart Image ──
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `📊 ${t.chartTitle}`,
              bold: true,
              size: 28,
              color: '0F6E56',
              font: 'Calibri',
            }),
          ],
          spacing: { after: 200 },
        })
      )

      if (chartBase64) {
        const imgBytes = base64ToUint8Array(chartBase64)
        children.push(
          new Paragraph({
            children: [
              new ImageRun({
                data: imgBytes,
                transformation: { width: 580, height: 350 },
                type: 'png',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 300 },
          })
        )
      } else {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: '[Chart image not available — please ensure the chart is visible on screen]',
                italics: true,
                color: '999999',
                size: 20,
              }),
            ],
            spacing: { after: 300 },
          })
        )
      }

      // ── Insights as Table ──
      if (aiStory.insights && aiStory.insights.length > 0) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `💡 ${t.insightsTitle}`,
                bold: true,
                size: 28,
                color: '534AB7',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 200 },
          })
        )

        const insightRows = aiStory.insights.map((ins) => {
          const iconMap = { positive: '✅', negative: '⚠️', neutral: 'ℹ️' }
          const colorMap = { positive: 'E1F5EE', negative: 'FCEBEB', neutral: 'EEEDFE' }
          const textColorMap = { positive: '085041', negative: 'A32D2D', neutral: '3C3489' }

          return new TableRow({
            children: [
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: iconMap[ins.type] || 'ℹ️',
                        size: 24,
                      }),
                    ],
                    alignment: AlignmentType.CENTER,
                  }),
                ],
                width: { size: 800, type: WidthType.DXA },
                shading: {
                  type: ShadingType.SOLID,
                  color: colorMap[ins.type] || 'EEEDFE',
                },
                verticalAlign: 'center',
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: ins.label,
                        bold: true,
                        size: 22,
                        color: textColorMap[ins.type] || '333333',
                        font: 'Calibri',
                      }),
                    ],
                  }),
                ],
                width: { size: 3200, type: WidthType.DXA },
                shading: {
                  type: ShadingType.SOLID,
                  color: colorMap[ins.type] || 'EEEDFE',
                },
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: String(ins.value),
                        bold: true,
                        size: 24,
                        color: textColorMap[ins.type] || '333333',
                        font: 'Calibri',
                      }),
                    ],
                    alignment: AlignmentType.RIGHT,
                  }),
                ],
                width: { size: 5000, type: WidthType.DXA },
                shading: {
                  type: ShadingType.SOLID,
                  color: colorMap[ins.type] || 'EEEDFE',
                },
              }),
            ],
          })
        })

        children.push(
          new Table({
            rows: insightRows,
            width: { size: 100, type: WidthType.PERCENTAGE },
          })
        )

        children.push(new Paragraph({ spacing: { after: 300 } }))
      }

      // ── Data Story ──
      if (aiStory.story) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `📖 ${t.storyTitle}`,
                bold: true,
                size: 28,
                color: '085041',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 100 },
          })
        )
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: aiStory.story,
                size: 22,
                color: '333333',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 300 },
            border: {
              left: { color: '9FE1CB', space: 5, style: BorderStyle.SINGLE, size: 12 },
            },
            indent: { left: 300 },
          })
        )
      }

      // ── Recommendation ──
      if (aiStory.recommendation) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `🎯 ${t.recommendTitle}`,
                bold: true,
                size: 28,
                color: '534AB7',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 100 },
          })
        )
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: aiStory.recommendation,
                size: 22,
                color: '333333',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 300 },
            border: {
              left: { color: 'AFA9EC', space: 5, style: BorderStyle.SINGLE, size: 12 },
            },
            indent: { left: 300 },
          })
        )
      }

      // ── Roadmap ──
      if (aiStory.roadmap) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `🗺️ ${t.roadmapTitle}`,
                bold: true,
                size: 28,
                color: '856404',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 100 },
          })
        )
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: aiStory.roadmap,
                size: 22,
                color: '333333',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 300 },
            border: {
              left: { color: 'FFEAA7', space: 5, style: BorderStyle.SINGLE, size: 12 },
            },
            indent: { left: 300 },
          })
        )
      }

      // ── Comprehensive Report ──
      if (aiStory.report) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `📑 ${t.reportTitle}`,
                bold: true,
                size: 28,
                color: '0C5460',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 100 },
          })
        )
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: aiStory.report,
                size: 22,
                color: '333333',
                font: 'Calibri',
              }),
            ],
            spacing: { after: 300 },
            border: {
              left: { color: 'BEE5EB', space: 5, style: BorderStyle.SINGLE, size: 12 },
            },
            indent: { left: 300 },
          })
        )
      }

      // ── Footer ──
      children.push(
        new Paragraph({
          border: {
            top: { color: 'CCCCCC', space: 1, style: BorderStyle.SINGLE, size: 6 },
          },
          spacing: { before: 400, after: 100 },
        })
      )
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `Smart Chart Builder  |  ${new Date().toLocaleDateString()}`,
              size: 16,
              color: 'AAAAAA',
              font: 'Calibri',
            }),
          ],
          alignment: AlignmentType.CENTER,
        })
      )

      // Build doc
      const doc = new Document({
        sections: [
          {
            properties: {
              page: {
                margin: { top: 720, bottom: 720, left: 720, right: 720 },
              },
            },
            children,
          },
        ],
      })

      const blob = await Packer.toBlob(doc)
      const fileName = (chartConfig.title || 'report').replace(/\s+/g, '_')
      saveAs(blob, `${fileName}_report.docx`)
    } catch (err) {
      console.error('DOCX generation error:', err)
      alert('DOCX generation failed: ' + err.message)
    } finally {
      setDownloading(false)
    }
  }, [canExport, chartConfig, aiStory, chartContainerId, lang, t])

  if (!canExport) {
    return (
      <div style={{
        background: '#fafafa', border: '1px dashed #ddd', borderRadius: 10,
        padding: '20px 14px', textAlign: 'center', color: '#999', fontSize: 12,
      }}>
        <span style={{ fontSize: 28, display: 'block', marginBottom: 8 }}>📋</span>
        {t.noData}
      </div>
    )
  }

  return (
    <div style={{
      background: '#fff', border: '1px solid #eee', borderRadius: 10,
      padding: 14, display: 'flex', flexDirection: 'column', gap: 10,
    }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ fontSize: 13, fontWeight: 600, color: '#333' }}>{t.title}</span>
      </div>

      {/* Mini Preview */}
      <div style={{
        background: 'linear-gradient(135deg, #f8f7ff 0%, #f0fdf8 100%)',
        border: '1px solid #e8e6f8', borderRadius: 8, padding: 12,
        fontSize: 11, color: '#555', lineHeight: 1.6,
      }}>
        <div style={{ fontWeight: 600, color: '#534AB7', marginBottom: 6, fontSize: 12 }}>
          {chartConfig.title || t.chartTitle}
        </div>
        <div style={{
          display: 'flex', gap: 6, marginBottom: 8, flexWrap: 'wrap',
        }}>
          {aiStory.insights?.map((ins, i) => {
            const c = INSIGHT_COLORS[ins.type] || INSIGHT_COLORS.neutral
            return (
              <span key={i} style={{
                background: c.bg, color: c.text, border: `1px solid ${c.border}`,
                padding: '2px 8px', borderRadius: 12, fontSize: 10, fontWeight: 500,
              }}>
                {c.label} {ins.label}: {ins.value}
              </span>
            )
          })}
        </div>
        {aiStory.story && (
          <div style={{ color: '#444', fontSize: 11 }}>
            {aiStory.story.length > 120 ? aiStory.story.slice(0, 120) + '...' : aiStory.story}
          </div>
        )}
      </div>

      {/* Edit Note */}
      <div style={{
        fontSize: 10, color: '#888', background: '#FFFDE7',
        border: '1px solid #FFF9C4', borderRadius: 6, padding: '6px 10px',
        lineHeight: 1.5,
      }}>
        {t.editNote}
      </div>

      {/* Download Button */}
      <button
        onClick={generateDocx}
        disabled={downloading}
        style={{
          width: '100%', padding: '10px 0', borderRadius: 8, border: 'none',
          background: downloading
            ? 'linear-gradient(135deg, #aaa, #999)'
            : 'linear-gradient(135deg, #534AB7, #7B68EE)',
          color: '#fff', fontSize: 13, fontWeight: 600, cursor: downloading ? 'not-allowed' : 'pointer',
          boxShadow: downloading ? 'none' : '0 2px 8px rgba(83,74,183,0.3)',
          transition: 'all 0.2s ease',
          letterSpacing: 0.5,
        }}
      >
        {downloading ? t.downloading : t.download}
      </button>
    </div>
  )
}
